import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://your-project.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'your-anon-key';

// Debug environment variables
console.log('🔍 Environment Variables Debug:');
console.log('VITE_SUPABASE_URL:', import.meta.env.VITE_SUPABASE_URL);
console.log('VITE_SUPABASE_ANON_KEY:', import.meta.env.VITE_SUPABASE_ANON_KEY ? 'Set' : 'Not set');
console.log('Final supabaseUrl:', supabaseUrl);
console.log('Final supabaseAnonKey:', supabaseAnonKey ? 'Set' : 'Not set');

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Database types (we'll generate these from Supabase)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          role: 'admin' | 'driver' | 'owner';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          first_name: string;
          last_name: string;
          role: 'admin' | 'driver' | 'owner';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          role?: 'admin' | 'driver' | 'owner';
          created_at?: string;
          updated_at?: string;
        };
      };
      companies: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          description: string | null;
          address_line1: string;
          address_line2: string | null;
          city: string;
          postcode: string;
          country: string;
          phone: string | null;
          email: string | null;
          website: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          description?: string | null;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          postcode: string;
          country: string;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo_url?: string | null;
          description?: string | null;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          postcode?: string;
          country?: string;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      drivers: {
        Row: {
          id: string;
          employee_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          license_number: string;
          license_expiry: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          postcode: string;
          country: string;
          status: 'active' | 'inactive' | 'suspended';
          hourly_rate: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          license_number: string;
          license_expiry: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          postcode: string;
          country: string;
          status?: 'active' | 'inactive' | 'suspended';
          hourly_rate: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          license_number?: string;
          license_expiry?: string;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          postcode?: string;
          country?: string;
          status?: 'active' | 'inactive' | 'suspended';
          hourly_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          registration: string;
          make: string;
          model: string;
          year: number;
          type: 'truck' | 'trailer' | 'van';
          capacity: number;
          status: 'active' | 'maintenance' | 'retired';
          last_service_date: string | null;
          next_service_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          registration: string;
          make: string;
          model: string;
          year: number;
          type: 'truck' | 'trailer' | 'van';
          capacity: number;
          status?: 'active' | 'maintenance' | 'retired';
          last_service_date?: string | null;
          next_service_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          registration?: string;
          make?: string;
          model?: string;
          year?: number;
          type?: 'truck' | 'trailer' | 'van';
          capacity?: number;
          status?: 'active' | 'maintenance' | 'retired';
          last_service_date?: string | null;
          next_service_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      jobs: {
        Row: {
          id: string;
          job_number: string;
          title: string;
          description: string;
          customer_name: string;
          customer_phone: string | null;
          customer_email: string | null;
          priority: 'low' | 'medium' | 'high' | 'urgent';
          status: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled';
          assigned_driver_id: string | null;
          assigned_vehicle_id: string | null;
          scheduled_date: string;
          scheduled_time: string;
          estimated_duration: number;
          actual_start_time: string | null;
          actual_end_time: string | null;
          pickup_address: any; // JSON
          delivery_address: any; // JSON
          cargo_type: string;
          cargo_weight: number;
          special_requirements: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_number: string;
          title: string;
          description: string;
          customer_name: string;
          customer_phone?: string | null;
          customer_email?: string | null;
          priority: 'low' | 'medium' | 'high' | 'urgent';
          status?: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled';
          assigned_driver_id?: string | null;
          assigned_vehicle_id?: string | null;
          scheduled_date: string;
          scheduled_time: string;
          estimated_duration: number;
          actual_start_time?: string | null;
          actual_end_time?: string | null;
          pickup_address: any;
          delivery_address: any;
          cargo_type: string;
          cargo_weight: number;
          special_requirements?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          job_number?: string;
          title?: string;
          description?: string;
          customer_name?: string;
          customer_phone?: string | null;
          customer_email?: string | null;
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          status?: 'pending' | 'assigned' | 'in_progress' | 'completed' | 'cancelled';
          assigned_driver_id?: string | null;
          assigned_vehicle_id?: string | null;
          scheduled_date?: string;
          scheduled_time?: string;
          estimated_duration?: number;
          actual_start_time?: string | null;
          actual_end_time?: string | null;
          pickup_address?: any;
          delivery_address?: any;
          cargo_type?: string;
          cargo_weight?: number;
          special_requirements?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      client_contacts: {
        Row: {
          id: string;
          name: string;
          company: string;
          position: string;
          email: string;
          phone: string | null;
          mobile: string | null;
          address_line1: string;
          address_line2: string | null;
          address_line3: string | null;
          town: string | null;
          city: string;
          postcode: string;
          country: string;
          category: 'client' | 'supplier' | 'partner' | 'prospect';
          status: 'active' | 'inactive' | 'lead';
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          company: string;
          position: string;
          email: string;
          phone?: string | null;
          mobile?: string | null;
          address_line1: string;
          address_line2?: string | null;
          address_line3?: string | null;
          town?: string | null;
          city: string;
          postcode: string;
          country: string;
          category: 'client' | 'supplier' | 'partner' | 'prospect';
          status?: 'active' | 'inactive' | 'lead';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          company?: string;
          position?: string;
          email?: string;
          phone?: string | null;
          mobile?: string | null;
          address_line1?: string;
          address_line2?: string | null;
          address_line3?: string | null;
          town?: string | null;
          city?: string;
          postcode?: string;
          country?: string;
          category?: 'client' | 'supplier' | 'partner' | 'prospect';
          status?: 'active' | 'inactive' | 'lead';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      fuel_records: {
        Row: {
          id: string;
          driver_id: string;
          vehicle_id: string;
          date: string;
          fuel_type: string;
          quantity: number;
          cost_per_litre: number;
          total_cost: number;
          mileage: number;
          location: string;
          receipt_url: string | null;
          status: 'pending' | 'approved' | 'rejected';
          approved_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          driver_id: string;
          vehicle_id: string;
          date: string;
          fuel_type: string;
          quantity: number;
          cost_per_litre: number;
          total_cost: number;
          mileage: number;
          location: string;
          receipt_url?: string | null;
          status?: 'pending' | 'approved' | 'rejected';
          approved_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          driver_id?: string;
          vehicle_id?: string;
          date?: string;
          fuel_type?: string;
          quantity?: number;
          cost_per_litre?: number;
          total_cost?: number;
          mileage?: number;
          location?: string;
          receipt_url?: string | null;
          status?: 'pending' | 'approved' | 'rejected';
          approved_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          invoice_number: string;
          customer_id: string | null;
          customer_name: string;
          customer_email: string | null;
          customer_phone: string | null;
          issue_date: string;
          due_date: string;
          status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          total_amount: number;
          paid_amount: number;
          outstanding_amount: number;
          job_reference: string | null;
          driver_name: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_number: string;
          customer_id?: string | null;
          customer_name: string;
          customer_email?: string | null;
          customer_phone?: string | null;
          issue_date: string;
          due_date: string;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total_amount?: number;
          paid_amount?: number;
          outstanding_amount?: number;
          job_reference?: string | null;
          driver_name?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_number?: string;
          customer_id?: string | null;
          customer_name?: string;
          customer_email?: string | null;
          customer_phone?: string | null;
          issue_date?: string;
          due_date?: string;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total_amount?: number;
          paid_amount?: number;
          outstanding_amount?: number;
          job_reference?: string | null;
          driver_name?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoice_line_items: {
        Row: {
          id: string;
          invoice_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          description: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          created_at?: string;
        };
      };
      purchase_orders: {
        Row: {
          id: string;
          order_number: string;
          supplier_id: string | null;
          supplier_name: string;
          supplier_email: string | null;
          supplier_phone: string | null;
          order_date: string;
          delivery_date: string | null;
          status: 'pending' | 'approved' | 'delivered' | 'cancelled';
          total_amount: number;
          category: string | null;
          requested_by: string | null;
          approved_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          supplier_id?: string | null;
          supplier_name: string;
          supplier_email?: string | null;
          supplier_phone?: string | null;
          order_date: string;
          delivery_date?: string | null;
          status?: 'pending' | 'approved' | 'delivered' | 'cancelled';
          total_amount?: number;
          category?: string | null;
          requested_by?: string | null;
          approved_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          supplier_id?: string | null;
          supplier_name?: string;
          supplier_email?: string | null;
          supplier_phone?: string | null;
          order_date?: string;
          delivery_date?: string | null;
          status?: 'pending' | 'approved' | 'delivered' | 'cancelled';
          total_amount?: number;
          category?: string | null;
          requested_by?: string | null;
          approved_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      purchase_order_line_items: {
        Row: {
          id: string;
          purchase_order_id: string;
          description: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          purchase_order_id: string;
          description: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          purchase_order_id?: string;
          description?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          created_at?: string;
        };
      };
      wage_slips: {
        Row: {
          id: string;
          slip_number: string;
          driver_id: string;
          pay_period_start: string;
          pay_period_end: string;
          pay_date: string;
          status: 'draft' | 'approved' | 'paid';
          basic_hours: number;
          basic_rate: number;
          basic_pay: number;
          overtime_hours: number;
          overtime_rate: number;
          overtime_pay: number;
          bonus: number;
          deductions: number;
          gross_pay: number;
          tax: number;
          national_insurance: number;
          pension: number;
          net_pay: number;
          created_by: string | null;
          approved_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slip_number: string;
          driver_id: string;
          pay_period_start: string;
          pay_period_end: string;
          pay_date: string;
          status?: 'draft' | 'approved' | 'paid';
          basic_hours?: number;
          basic_rate?: number;
          basic_pay?: number;
          overtime_hours?: number;
          overtime_rate?: number;
          overtime_pay?: number;
          bonus?: number;
          deductions?: number;
          gross_pay?: number;
          tax?: number;
          national_insurance?: number;
          pension?: number;
          net_pay?: number;
          created_by?: string | null;
          approved_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slip_number?: string;
          driver_id?: string;
          pay_period_start?: string;
          pay_period_end?: string;
          pay_date?: string;
          status?: 'draft' | 'approved' | 'paid';
          basic_hours?: number;
          basic_rate?: number;
          basic_pay?: number;
          overtime_hours?: number;
          overtime_rate?: number;
          overtime_pay?: number;
          bonus?: number;
          deductions?: number;
          gross_pay?: number;
          tax?: number;
          national_insurance?: number;
          pension?: number;
          net_pay?: number;
          created_by?: string | null;
          approved_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      manifests: {
        Row: {
          id: string;
          manifest_number: string;
          driver_id: string | null;
          vehicle_id: string | null;
          manifest_date: string;
          route_name: string | null;
          total_deliveries: number;
          total_weight: number;
          status: 'draft' | 'printed' | 'completed';
          created_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          manifest_number: string;
          driver_id?: string | null;
          vehicle_id?: string | null;
          manifest_date: string;
          route_name?: string | null;
          total_deliveries?: number;
          total_weight?: number;
          status?: 'draft' | 'printed' | 'completed';
          created_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          manifest_number?: string;
          driver_id?: string | null;
          vehicle_id?: string | null;
          manifest_date?: string;
          route_name?: string | null;
          total_deliveries?: number;
          total_weight?: number;
          status?: 'draft' | 'printed' | 'completed';
          created_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      manifest_deliveries: {
        Row: {
          id: string;
          manifest_id: string;
          job_id: string | null;
          delivery_sequence: number;
          customer_name: string;
          delivery_address: any;
          contact_person: string | null;
          contact_phone: string | null;
          delivery_instructions: string | null;
          cargo_description: string | null;
          weight: number | null;
          delivery_time: string | null;
          status: 'pending' | 'delivered' | 'failed';
          signature_url: string | null;
          photo_url: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          manifest_id: string;
          job_id?: string | null;
          delivery_sequence: number;
          customer_name: string;
          delivery_address: any;
          contact_person?: string | null;
          contact_phone?: string | null;
          delivery_instructions?: string | null;
          cargo_description?: string | null;
          weight?: number | null;
          delivery_time?: string | null;
          status?: 'pending' | 'delivered' | 'failed';
          signature_url?: string | null;
          photo_url?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          manifest_id?: string;
          job_id?: string | null;
          delivery_sequence?: number;
          customer_name?: string;
          delivery_address?: any;
          contact_person?: string | null;
          contact_phone?: string | null;
          delivery_instructions?: string | null;
          cargo_description?: string | null;
          weight?: number | null;
          delivery_time?: string | null;
          status?: 'pending' | 'delivered' | 'failed';
          signature_url?: string | null;
          photo_url?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      timesheets: {
        Row: {
          id: string;
          driver_id: string;
          week_start_date: string;
          week_end_date: string;
          total_hours: number;
          regular_hours: number;
          overtime_hours: number;
          status: 'draft' | 'submitted' | 'approved' | 'paid';
          submitted_at: string | null;
          approved_by: string | null;
          approved_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          driver_id: string;
          week_start_date: string;
          week_end_date: string;
          total_hours?: number;
          regular_hours?: number;
          overtime_hours?: number;
          status?: 'draft' | 'submitted' | 'approved' | 'paid';
          submitted_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          driver_id?: string;
          week_start_date?: string;
          week_end_date?: string;
          total_hours?: number;
          regular_hours?: number;
          overtime_hours?: number;
          status?: 'draft' | 'submitted' | 'approved' | 'paid';
          submitted_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      timesheet_entries: {
        Row: {
          id: string;
          timesheet_id: string;
          job_id: string | null;
          date: string;
          start_time: string;
          end_time: string;
          break_duration: number;
          total_hours: number;
          hourly_rate: number;
          total_pay: number;
          is_overtime: boolean;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          timesheet_id: string;
          job_id?: string | null;
          date: string;
          start_time: string;
          end_time: string;
          break_duration?: number;
          total_hours: number;
          hourly_rate: number;
          total_pay: number;
          is_overtime?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          timesheet_id?: string;
          job_id?: string | null;
          date?: string;
          start_time?: string;
          end_time?: string;
          break_duration?: number;
          total_hours?: number;
          hourly_rate?: number;
          total_pay?: number;
          is_overtime?: boolean;
          description?: string | null;
          created_at?: string;
        };
      };
      expense_claims: {
        Row: {
          id: string;
          claim_number: string;
          driver_id: string;
          claim_date: string;
          total_amount: number;
          status: 'draft' | 'submitted' | 'approved' | 'paid' | 'rejected';
          submitted_at: string | null;
          approved_by: string | null;
          approved_at: string | null;
          rejection_reason: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          claim_number: string;
          driver_id: string;
          claim_date: string;
          total_amount?: number;
          status?: 'draft' | 'submitted' | 'approved' | 'paid' | 'rejected';
          submitted_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          rejection_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          claim_number?: string;
          driver_id?: string;
          claim_date?: string;
          total_amount?: number;
          status?: 'draft' | 'submitted' | 'approved' | 'paid' | 'rejected';
          submitted_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          rejection_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      expense_claim_items: {
        Row: {
          id: string;
          expense_claim_id: string;
          date: string;
          description: string;
          category: string;
          amount: number;
          receipt_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          expense_claim_id: string;
          date: string;
          description: string;
          category: string;
          amount: number;
          receipt_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          expense_claim_id?: string;
          date?: string;
          description?: string;
          category?: string;
          amount?: number;
          receipt_url?: string | null;
          created_at?: string;
        };
      };
      vehicle_maintenance: {
        Row: {
          id: string;
          vehicle_id: string;
          maintenance_type: string;
          description: string;
          maintenance_date: string;
          mileage: number;
          cost: number;
          garage_name: string | null;
          garage_contact: string | null;
          next_service_date: string | null;
          next_service_mileage: number | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          created_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vehicle_id: string;
          maintenance_type: string;
          description: string;
          maintenance_date: string;
          mileage: number;
          cost?: number;
          garage_name?: string | null;
          garage_contact?: string | null;
          next_service_date?: string | null;
          next_service_mileage?: number | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          created_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vehicle_id?: string;
          maintenance_type?: string;
          description?: string;
          maintenance_date?: string;
          mileage?: number;
          cost?: number;
          garage_name?: string | null;
          garage_contact?: string | null;
          next_service_date?: string | null;
          next_service_mileage?: number | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          created_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      compliance_documents: {
        Row: {
          id: string;
          driver_id: string | null;
          vehicle_id: string | null;
          document_type: string;
          document_name: string;
          document_number: string | null;
          issue_date: string | null;
          expiry_date: string;
          document_url: string | null;
          status: 'valid' | 'expired' | 'expiring_soon' | 'invalid';
          reminder_sent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          driver_id?: string | null;
          vehicle_id?: string | null;
          document_type: string;
          document_name: string;
          document_number?: string | null;
          issue_date?: string | null;
          expiry_date: string;
          document_url?: string | null;
          status?: 'valid' | 'expired' | 'expiring_soon' | 'invalid';
          reminder_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          driver_id?: string | null;
          vehicle_id?: string | null;
          document_type?: string;
          document_name?: string;
          document_number?: string | null;
          issue_date?: string | null;
          expiry_date?: string;
          document_url?: string | null;
          status?: 'valid' | 'expired' | 'expiring_soon' | 'invalid';
          reminder_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']> = Database['public'][T];
